---
language: ruby
cache: bundler
rvm:
  - 2.7.2
env:
  global:
    - AWS_KEY=AWS_KEY
    - AWS_SECRET=AWS_SECRET
    - AWS_REGION="us-east-2"
    - VAULT_NAME=VAULT_NAME
before_install: gem install bundler -v 2.1.4
services:
  - redis-server
  - postgresql
